version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: xss_demo
      MYSQL_USER: xss_demo_user
      MYSQL_PASSWORD: xss_demo_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
